# Generated by Django 5.1.7 on 2025-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=105)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField(default=0)),
                ('Category', models.CharField(choices=[('electronics', 'Electronics'), ('shoes', 'Shoes'), ('wears', 'Wears'), ('accessories', 'Accessories'), ('skincare', 'Skincare')], default='electronics', max_length=20)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
